#!/usr/bin/env bash
# creation of script that take arg and send fl from local to serv
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp  -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
