#!/usr/bin/env bash
# t1

apt-get update
apt-get install haproxy -y

echo "
frontend eyes
    bind *:80
    default_backend heart

backend heart
    balance roundrobin
    server 387178-web-01 100.26.250.121:80 check
    server 387178-web-02 54.164.174.101:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
