#!/usr/bin/env bash
# t1

apt-get update
apt-get install haproxy

echo "
frontend eyes
    bind *:80
    default_backend heart

backend heart
    balance roundrobin
    server 387178-web-01 100.25.19.136:80 check
    server 387178-web-02 35.174.205.13:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
