#!/usr/bin/env bash
# t1

apt-get update
apt-get install haproxy

echo  "\nfrontend cfg_front\n\tlisten load_listener\n\tmode http\n\toption httpclose\n
\tdefault_backend cfg_back\nbackend cfg_back\n\tbalance roundrobin\n\tserver 365672-web-01 100.26.250.121:80 check\n\tserver 3365672-web-02 54.164.174.101:80 check\n" >> /etc/haproxy/haproxy.cfg
